sudo: required

services:
- docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - secure: MpxpTwD7f0CNEVLitSpVmocK7O9r+BwFE1deEHK4AlQo/oc9cOlhGe1EL3mx9zbglPmjlDg/8kMUGv6vSirIabfBo9Szjps76bHckFr9lr2Ykkg0e29oC8pgPpSXD1eY/1ZIN/FvIkxpUFLETo1okS/j9q/A0DCGFmti0n3EoMORsgRz9CpNAiEh0zpSd6+euPAGHuczuCrDuO84my9bIOCjA/+aPunHNeXiuM8yIM2SxCSyGtIKT0+jvquIvLF58VxivysXBlRfhDn8fhB09nXA2Ru/derYQACfcmNSn9Pd4bDpebPJW5B9H/XA8xjb58uKinUlncbAMB/QnxoT75j9YRWJZRSQ+34XNYP6ZgK9soZ2TC6djQyEKTUu45Kp/1s+poSn42m9jytJJTmmK0KxsZTRcC8JD5nrjIMZWPUNNTwC5L4+I7ZRWg2WooK3LNyq1Ng8Hn6W77wSgsvAJw2HD3Lx58AprGUhHuBeaIZRuSN9aKwZrl9vKQJLqPnOp/nF2EC6kot5HYYtcotGtETXPUDih21gWD5ZM2BqVqYfQQnJnNMgeYmMdj6QQuTFqhuNJf7hXRIRkTnD3j1gDOLKQZazW0+N2JE8XWDFwi6fKScDsxT85lJti9HmzHa7+k4RVHmUYuDgRoPuzUgjWHvPsiz3/Z8WQ9JYpH84S8w=
    - secure: fWzZisT6nGDNL4lf6tXB07eFG2drgBakHxzdF/NFVvzuP861RFR6omuL+ED0PgXrEHDJBxaBLv52je8irmUXrAH1CNr7T8DWiZo/h5h609Uzr+38T1NnIu4krL0Wo6/CDwlLKnzqTq9yBIZLQSHVJmo8AOpo1JPIi2ajodqj9ZfmAxDQTQl+G6zvQjtqIkYHsHY7A44Rto0f14ykn7w2S82Jn6Ry89VNI5V1WEO3sMpM/XekNP/HokNcRIuntL/0+kuLvTJ5akGoTjBQxSnSW95opzPeGky74HRU2obExJYqKvF0VfVJRNAqejwjIiFIbbjqV0Sk5391kFuhuBErQQDM1bOHGdxZ41HsJH29qNWIl7C33Yl10qERoqecgsJ1N/bS2ZEmWqm/zQh5GClCXPvYmzEqMYsMGM3vjbKdjDlc1Wh2w/eFclsXN9LSXh1mc35rtj46frcT6e5Kof87AIfC9hTgDvk9kAsyjaHMkSHSZthbZXCIcsD8qriNm5UqfFBYD79mPIP1S2YMQ2jscCsjHOZgYVrcm0kzDF21J1w6H0Lo7d1jw37LYlegBdtLQ9gYgqY2D5m+nxWuVoD5FZmpR+5JGtK+ootyLFF8aiFoHXd4op1JCxRLjgkmnZKXzw3kTQSpE7oa7CgzchtQmK2nqcqla1b5Qk7ilVcjooo=

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > docker-compose
  - sudo mv docker-compose /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

jobs:  
  include:
    - stage: "Build"
      name: "mailcow/acme"
      script:
      - export BUILDCONTAINER=mailcow/acme
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/unbound"   
      script:
      - export BUILDCONTAINER=mailcow/unbound
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/clamd"   
      script:
      - export BUILDCONTAINER=mailcow/clamd
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/rspamd"   
      script:
      - export BUILDCONTAINER=mailcow/rspamd
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/phpfpm"
      script:
      - export BUILDCONTAINER=mailcow/phpfpm
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/sogo"   
      script:
      - export BUILDCONTAINER=mailcow/sogo
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/dovecot"   
      script:
      - export BUILDCONTAINER=mailcow/dovecot
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/postfix"   
      script:
      - export BUILDCONTAINER=mailcow/postfix
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/netfilter"   
      script:
      - export BUILDCONTAINER=mailcow/netfilter
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/watchdog"   
      script:
      - export BUILDCONTAINER=mailcow/watchdog
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/dockerapi"   
      script:
      - export BUILDCONTAINER=mailcow/dockerapi
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
    - name: "mailcow/solr"
      script:
      - export BUILDCONTAINER=mailcow/solr
      - echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - chmod +x ./helper-scripts/travis-ci.sh && ./helper-scripts/travis-ci.sh
branches:
  only:
  - master
